/* 
**  mod_mytest.c -- Apache sample mytest module
**  [Autogenerated via ``apxs -n mytest -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_mytest.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /mytest in as follows:
**
**    #   apache2.conf
**    LoadModule mytest_module modules/mod_mytest.so
**    <Location /mytest>
**    SetHandler mytest
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /mytest and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/mytest 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_mytest.c
*/ 

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/time.h>
#include <hiredis/hiredis.h>
#include <postgresql/libpq-fe.h>

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "http_log.h"

/* The sample content handler */
static int mytest_handler(request_rec *r)
{
	redisContext *rdconn;
	PGconn *pgconn;

    if (strcmp(r->handler, "mytest")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only){
        ap_rputs("The sample page from mod_mytest.c\n", r);

		rdconn = redisConnect("127.0.0.1", 6379);
		if (!rdconn) {
			ap_rputs("redisConnect error\n", r);
			return OK;
 		}
		if (rdconn->err) {
			ap_log_rerror(APLOG_MARK, APLOG_CRIT, 0, r,"%s", rdconn->errstr);
			ap_rputs("redisConnect error\n", r);
			redisFree(rdconn);
			return OK;
		}

		pgconn = PQconnectdb( "host=127.0.0.1 port=5432 dbname=ekidb" );
		if(!pgconn || PQstatus( pgconn ) == CONNECTION_BAD ){
			ap_rputs("PQconnectdb error\n", r);
			if(pgconn){
				PQfinish(pgconn);
			}
			redisFree(rdconn);
			return OK;
		}

		ap_rputs("redisConnect/PQconnectdb SUCCESS\n", r);

		PQfinish(pgconn);
		redisFree(rdconn);
	}

    return OK;
}

static void mytest_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(mytest_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA mytest_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    mytest_register_hooks  /* register hooks                      */
};

